#!/bin/bash
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=1
#PBS -N                             ne21
#PBS -o                 exps_linear/ne21.txt
#PBS -e                 exps_linear/ne21_e.txt 

module load matlab
matlab -nodisplay -nosplash -r options21
