#!/bin/bash
#PBS -N smooth_Atide0.08_Nx80Ny200Nr318_spin 
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q regular
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=1
#PBS -o output.txt
#PBS -e errors.txt

module load matlab

matlab create_exps.m