#!/bin/bash
#PBS -N lam 
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=1
#PBS -o output.txt
#PBS -e errors.txt

module load matlab

matlab create_exps.m
