qsub run_matlab_derecho1 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho2 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho3 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho4 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho5 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho6 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho7 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho8 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho9 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho10 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho11 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho12 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho13 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho14 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho15 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho16 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho17 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho18 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho19 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho20 > exps_tanh_ZeroBottom_dz2/output.txt
qsub run_matlab_derecho21 > exps_tanh_ZeroBottom_dz2/output.txt
