qsub run_matlab_derecho13 > exps_linear/output.txt
qsub run_matlab_derecho14 > exps_linear/output.txt
qsub run_matlab_derecho15 > exps_linear/output.txt
qsub run_matlab_derecho16 > exps_linear/output.txt
qsub run_matlab_derecho17 > exps_linear/output.txt
qsub run_matlab_derecho18 > exps_linear/output.txt
qsub run_matlab_derecho19 > exps_linear/output.txt
qsub run_matlab_derecho20 > exps_linear/output.txt
qsub run_matlab_derecho21 > exps_linear/output.txt
