#!/bin/bash
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=2:ncpus=128:mpiprocs=128:ompthreads=1
#PBS -N options_parallel1_random3
#PBS -o shear_methieu_noDiff_random3/ns1.txt
#PBS -e shear_methieu_noDiff_random3/ns1_e.txt 

module load matlab
matlab -nodisplay -nosplash -r options_parallel1_random3
