qsub run_matlab_derecho1 > eigenvalues/eig_flat_kv2e-4/out1.txt
qsub run_matlab_derecho2 > eigenvalues/eig_flat_kv2e-4/out2.txt
qsub run_matlab_derecho3 > eigenvalues/eig_flat_kv2e-4/out3.txt
qsub run_matlab_derecho4 > eigenvalues/eig_flat_kv2e-4/out4.txt
qsub run_matlab_derecho5 > eigenvalues/eig_flat_kv2e-4/out5.txt
qsub run_matlab_derecho6 > eigenvalues/eig_flat_kv2e-4/out6.txt
qsub run_matlab_derecho7 > eigenvalues/eig_flat_kv2e-4/out7.txt
qsub run_matlab_derecho8 > eigenvalues/eig_flat_kv2e-4/out8.txt
qsub run_matlab_derecho9 > eigenvalues/eig_flat_kv2e-4/out9.txt
qsub run_matlab_derecho10 > eigenvalues/eig_flat_kv2e-4/out10.txt
