qsub run_matlab_derecho1 > eigenvalues/eig_flat_kv8e-5/out1.txt
qsub run_matlab_derecho2 > eigenvalues/eig_flat_kv8e-5/out2.txt
qsub run_matlab_derecho3 > eigenvalues/eig_flat_kv8e-5/out3.txt
qsub run_matlab_derecho4 > eigenvalues/eig_flat_kv8e-5/out4.txt
qsub run_matlab_derecho5 > eigenvalues/eig_flat_kv8e-5/out5.txt
qsub run_matlab_derecho6 > eigenvalues/eig_flat_kv8e-5/out6.txt
qsub run_matlab_derecho7 > eigenvalues/eig_flat_kv8e-5/out7.txt
qsub run_matlab_derecho8 > eigenvalues/eig_flat_kv8e-5/out8.txt
qsub run_matlab_derecho9 > eigenvalues/eig_flat_kv8e-5/out9.txt
qsub run_matlab_derecho10 > eigenvalues/eig_flat_kv8e-5/out10.txt
