#!/bin/bash
#PBS -N l100-s2.3
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=1
#PBS -o exps_RK4/output_lambda100_largeshear.txt
#PBS -e exps_RK4/errors_lambda100_largeshear.txt

module load matlab

matlab -nodisplay -nosplash -r run_create_exps
