#!/bin/bash
#PBS -N Nr100-1
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=1
#PBS -o exps_test_Nr100/Nr100-1.txt
#PBS -e exps_test_Nr100/Nr100-1-error.txt 

module load matlab

matlab -nodisplay -nosplash -r run_create_exps
