#!/bin/bash
#PBS -N exps_test_part3 
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=1
#PBS -o exps_test/out3.txt
#PBS -e exps_test/error3.txt 

module load matlab

matlab -nodisplay -nosplash -r options 
