#!/bin/bash
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=3:ncpus=128:mpiprocs=128:ompthreads=1
#PBS -N test
#PBS -o exps_new/o.txt
#PBS -e exps_new/e.txt 

module load matlab
matlab -nodisplay -nosplash -r options_parallel_rw
