#!/bin/bash
#PBS -A UMIT0054 
#PBS -m abe
#PBS -M y_si@mit.edu
#PBS -q main
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=128:mpiprocs=128:ompthreads=1
#PBS -N options_parallel_rw6
#PBS -o exps_varyingN/o6.txt
#PBS -e exps_varyingN/e6.txt 

module load matlab
matlab -nodisplay -nosplash -r options_parallel_rw6
