qsub run_matlab_derecho1 > exps_new/flat_kv2e-4/out1.txt
qsub run_matlab_derecho2 > exps_new/flat_kv2e-4/out2.txt
qsub run_matlab_derecho3 > exps_new/flat_kv2e-4/out3.txt
qsub run_matlab_derecho4 > exps_new/flat_kv2e-4/out4.txt
qsub run_matlab_derecho5 > exps_new/flat_kv2e-4/out5.txt
qsub run_matlab_derecho6 > exps_new/flat_kv2e-4/out6.txt
qsub run_matlab_derecho7 > exps_new/flat_kv2e-4/out7.txt
qsub run_matlab_derecho8 > exps_new/flat_kv2e-4/out8.txt
qsub run_matlab_derecho9 > exps_new/flat_kv2e-4/out9.txt
qsub run_matlab_derecho10 > exps_new/flat_kv2e-4/out10.txt
